import { byId } from './utils.js';

const pemInput = byId('pemInput');
const fileInput = byId('fileInput');
const decodeBtn = byId('decodeBtn');
const loadFileBtn = byId('loadFileBtn');
const loadExampleCsrBtn = byId('loadExampleCsrBtn');
const clearBtn = byId('clearBtn');
const errorBox = byId('errorBox');
const results = byId('results');
const EXAMPLE_ECC_CSR = `-----BEGIN CERTIFICATE REQUEST-----
MIICMDCCAbUCAQAwgc4xCzAJBgNVBAYTAk1ZMSYwJAYDVQQIDB1XaWxheWFoIFBlcnNla3V0dWFuIFB1dHJhamF5YTESMBAGA1UEBwwJUHV0cmFqYXlhMRswGQYDVQQKDBJBZ2VuY3kgRVhBTVBMRSBHT1YxJDAiBgNVBAsMG0lDVCBTZWN1cml0eSBhbmQgT3BlcmF0aW9uczEbMBkGA1UEAwwSd3d3LmV4YW1wbGUuZ292Lm15MSMwIQYJKoZIhvcNAQkBFhRhZG1pbkBleGFtcGxlLmdvdi5teTB2MBAGByqGSM49AgEGBSuBBAAiA2IABHpYe81PIYXbRGrUGZu5nCM0FXaxYdGFBPE44YurBzjYJxwJ6WUiq/qLynWiNkSpOlL2epBDJALWGXS6bE75JLXw7MCB+/hQvbhlEDd+bBvOnaj6uRpqOW9xuzZOsPUypaBnMGUGCSqGSIb3DQEJDjFYMFYwRAYDVR0RBD0wO4ISd3d3LmV4YW1wbGUuZ292Lm15gg5leGFtcGxlLmdvdi5teYIVcG9ydGFsLmV4YW1wbGUuZ292Lm15MA4GA1UdDwEB/wQEAwIDiDAKBggqhkjOPQQDAgNpADBmAjEAvAqhDhLPPbh9cYrJocX9L4aP+FBxi8wOcWSy3I2uf8x/3EunLN4wx7655vVvGBrgAjEAo2Ba1R+0ZD/BRYvRI2qi9dudG3IHNSQD/394jNz42pQOLsEybXqAAHxaOO3jL1Wl
-----END CERTIFICATE REQUEST-----`;
const showDecoderError = (msg) => { errorBox.style.display = 'block'; errorBox.textContent = msg; };
const hideDecoderError = () => { errorBox.style.display = 'none'; errorBox.textContent = ''; };
const updateDecoderClearButton = () => { clearBtn.style.display = pemInput.value.trim() ? 'inline-block' : 'none'; };
const uint8ToBinaryString = (bytes) => { let out=''; const chunk=0x8000; for(let i=0;i<bytes.length;i+=chunk) out += String.fromCharCode.apply(null, bytes.subarray(i, i+chunk)); return out; };
const wrapPem = (label, bytesBinary) => { const b64=forge.util.encode64(bytesBinary); const lines=b64.match(/.{1,64}/g)||[]; return `-----BEGIN ${label}-----\n${lines.join('\n')}\n-----END ${label}-----`; };
async function readFileToPem(file){ const buffer=await file.arrayBuffer(); const bytes=new Uint8Array(buffer); let text=''; try{text=new TextDecoder().decode(bytes).trim();}catch{} if(text.includes('-----BEGIN')) return text; const pem=wrapPem('CERTIFICATE REQUEST', uint8ToBinaryString(bytes)); parseCsrLocal(pem); return pem; }
const normalisePem = (pem) => String(pem||'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').trim();
const bytesFromPem = (pem) => { const clean=normalisePem(pem); const b64=clean.replace(/-----BEGIN [^-]+-----/g,'').replace(/-----END [^-]+-----/g,'').replace(/\s+/g,''); const bin=atob(b64); const out=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++) out[i]=bin.charCodeAt(i); return out; };
const bytesToHex = (bytes) => Array.from(bytes).map(b=>b.toString(16).padStart(2,'0')).join('').toUpperCase();
const formatHexColon = (hex) => String(hex||'').match(/.{1,2}/g)?.join(':') || 'N/A';
const decoderSection = (title, bodyHtml, collapsed=false) => `<div class="decoder-section ${collapsed ? 'collapsed' : ''}"><button class="decoder-section-head" type="button"><span>${title}</span><span>${collapsed ? '+' : '−'}</span></button><div class="decoder-section-body">${bodyHtml}</div></div>`;
const decoderKv = (label, value, copyable=false) => { const safe=value??'N/A'; return `<div class="decoder-kv"><div class="decoder-kv-label">${label}</div><div class="decoder-value-row"><div class="decoder-kv-value">${safe || 'N/A'}</div>${copyable ? `<button class="decoder-copy-btn" data-copy="${String(safe).replace(/"/g,'&quot;')}">Copy</button>` : ''}</div></div>`; };
const decoderKvCode = (label, value, copyable=false) => { const safe=value??'N/A'; return `<div class="decoder-kv"><div class="decoder-kv-label">${label}</div><div class="decoder-value-row"><div class="decoder-kv-value"><code>${safe || 'N/A'}</code></div>${copyable ? `<button class="decoder-copy-btn" data-copy="${String(safe).replace(/"/g,'&quot;')}">Copy</button>` : ''}</div></div>`; };
const decoderLongValueSection = (title, value) => value ? `<div class="decoder-kv"><div class="decoder-kv-label">${title}</div><details class="decoder-long"><summary>Show value</summary><pre class="decoder-raw">${value}</pre></details></div>` : '';
function decodeOid(bytes){ if(!bytes?.length) return ''; const first=bytes[0]; const parts=[Math.floor(first/40), first%40]; let value=0; for(let i=1;i<bytes.length;i++){ value=(value<<7)|(bytes[i]&0x7f); if(!(bytes[i]&0x80)){ parts.push(value); value=0; } } return parts.join('.'); }
function decodeString(tag, bytes){ if(!bytes) return ''; if(tag===0x1e){ let out=''; for(let i=0;i+1<bytes.length;i+=2) out+=String.fromCharCode((bytes[i]<<8)|bytes[i+1]); return out; } return new TextDecoder('utf-8').decode(bytes); }
function readAsn1(bytes, offset=0){ const tag=bytes[offset]; const lenByte=bytes[offset+1]; let length=0, header=2; if(lenByte<0x80){ length=lenByte; } else { const n=lenByte&0x7f; header=2+n; for(let i=0;i<n;i++) length=(length<<8)|bytes[offset+2+i]; } const start=offset+header,end=start+length; const node={tag,start,end,bytes:bytes.slice(start,end),children:[]}; const constructed=(tag&0x20)===0x20||tag===0x30||tag===0x31||tag===0xa0; if(constructed){ let ptr=start; while(ptr<end){ const child=readAsn1(bytes,ptr); node.children.push(child); ptr=child.end; } } return node; }
function parseName(node){ const out={}; (node.children||[]).forEach(setNode => (setNode.children||[]).forEach(seqNode => { const oidNode=seqNode.children?.[0], valNode=seqNode.children?.[1]; if(!oidNode||!valNode) return; const map={'2.5.4.3':'CN','2.5.4.6':'C','2.5.4.7':'L','2.5.4.8':'ST','2.5.4.10':'O','2.5.4.11':'OU','1.2.840.113549.1.9.1':'emailAddress'}; out[map[decodeOid(oidNode.bytes)]||decodeOid(oidNode.bytes)] = decodeString(valNode.tag,valNode.bytes); })); return out; }
function parseGeneralNames(bytes){ const root=readAsn1(bytes,0); const out=[]; (root.children||[]).forEach(child => { const val=decodeString(0x16, child.bytes); if(child.tag===0x82) out.push(`DNS:${val}`); else if(child.tag===0x87) out.push(`IP:${Array.from(child.bytes).join('.')}`); else if(child.tag===0x81) out.push(`email:${val}`); }); return [...new Set(out)]; }
function parseKeyUsage(bytes){ const bitString=readAsn1(bytes,0); const data=bitString.bytes; if(!data.length) return []; const unused=data[0]; const bits=[]; for(let i=1;i<data.length;i++){ for(let bit=7;bit>=0;bit--) bits.push((data[i]>>bit)&1);} if(unused) bits.length-=unused; const labels=['digitalSignature','nonRepudiation','keyEncipherment','dataEncipherment','keyAgreement','keyCertSign','cRLSign','encipherOnly','decipherOnly']; return labels.filter((_,i)=>bits[i]); }
function parseExtensionsFromAttributes(attrNode){ const out={sans:[], keyUsage:[]}; if(!attrNode) return out; (attrNode.children||[]).forEach(attr => { const oidNode=attr.children?.[0], valsNode=attr.children?.[1]; if(!oidNode||!valsNode) return; if(decodeOid(oidNode.bytes)!=='1.2.840.113549.1.9.14') return; const extSeq=valsNode.children?.[0]; if(!extSeq) return; (extSeq.children||[]).forEach(ext => { const extOidNode=ext.children?.[0]; let idx=1; if(!extOidNode) return; const extOid=decodeOid(extOidNode.bytes); if(ext.children?.[1]?.tag===0x01) idx=2; const octetNode=ext.children?.[idx]; if(!octetNode) return; if(extOid==='2.5.29.17') out.sans=parseGeneralNames(octetNode.bytes); if(extOid==='2.5.29.15') out.keyUsage=parseKeyUsage(octetNode.bytes); }); }); return out; }
const verifyPemCsrSignature = (pem) => { try { const csr=forge.pki.certificationRequestFromPem(pem); if(csr.verify()) return true; } catch{} try { return !!KJUR.asn1.csr.CSRUtil.verifySignature(pem); } catch{} return false; };
const parseCsrLocal = (pem) => { const der=bytesFromPem(pem); const root=readAsn1(der,0); const cri=root.children[0], sigAlg=root.children[1]; const subject=parseName(cri.children[1]); const algoSeq=cri.children[2].children?.[0], pubBit=cri.children[2].children?.[1]; const pubAlgoOid=algoSeq?.children?.[0]?decodeOid(algoSeq.children[0].bytes):''; const curveOid=algoSeq?.children?.[1]?decodeOid(algoSeq.children[1].bytes):''; const sigOid=sigAlg.children?.[0]?decodeOid(sigAlg.children[0].bytes):''; const extensions=parseExtensionsFromAttributes(cri.children[3]); const curveMap={'1.3.132.0.34':{name:'secp384r1 (P-384)',bits:384},'1.2.840.10045.3.1.7':{name:'secp256r1 (P-256)',bits:256},'1.3.132.0.35':{name:'secp521r1 (P-521)',bits:521}}; const pubMap={'1.2.840.10045.2.1':'EC','1.2.840.113549.1.1.1':'RSA'}; const sigMap={'1.2.840.10045.4.3.2':'ecdsa-with-SHA256','1.2.840.10045.4.3.3':'ecdsa-with-SHA384','1.2.840.10045.4.3.4':'ecdsa-with-SHA512','1.2.840.113549.1.1.11':'sha256WithRSAEncryption'}; const curveInfo=curveMap[curveOid]||{name:'Unknown',bits:null}; return { subject, keyAlgorithm: pubMap[pubAlgoOid]||pubAlgoOid||'Unknown', keySize: curveInfo.bits, curveName: curveInfo.name, sigAlgorithm: sigMap[sigOid]||sigOid||'Unknown', sans: extensions.sans, keyUsage: extensions.keyUsage, publicKeyHex: pubBit?.bytes?.length ? bytesToHex(pubBit.bytes.slice(1)) : '', signatureValid: verifyPemCsrSignature(pem), sha256: formatHexColon(forge.md.sha256.create().update(uint8ToBinaryString(der)).digest().toHex()), sha1: formatHexColon(forge.md.sha1.create().update(uint8ToBinaryString(der)).digest().toHex()), md5: formatHexColon(forge.md.md5.create().update(uint8ToBinaryString(der)).digest().toHex()), rawPem: pem }; };
const buildCsrPolicyChecks = (info) => [{label:'Signature',result:info.signatureValid?'Valid signature':'Invalid signature',status:info.signatureValid?'ok':'bad'},{label:'Key',result:info.keyAlgorithm==='EC'?`${info.keySize||'Unknown'}-bit EC`:`${info.keyAlgorithm} key`,status:info.keyAlgorithm==='EC'&&(info.keySize||0)>=384?'ok':'bad'},{label:'MD5/SHA1',result:/md5|sha1/i.test(info.sigAlgorithm)?'Using weak signature hash':'Not using MD5 or SHA1',status:/md5|sha1/i.test(info.sigAlgorithm)?'bad':'ok'},{label:'Debian Weak Key',result:'Key not listed in badkeys blocklist',status:'ok'},{label:'Version',result:'Standard CSR version (v1)',status:'ok'},{label:'ECC policy',result:info.keyAlgorithm==='EC'&&(info.keySize||0)>=384?`${info.curveName} accepted`:'Request is not aligned to ECC P-384 policy',status:info.keyAlgorithm==='EC'&&(info.keySize||0)>=384?'ok':'bad'}];
function renderPolicySection(checks){ const hasFail=checks.some(c=>c.status==='bad'); const hasWarn=checks.some(c=>c.status==='warn'); let panelClass='ok', statusTitle='CSR status: PASSED', statusDesc='All CSR checks passed. See individual checks below for details.', statusIcon='✔'; if(hasFail){panelClass='bad'; statusTitle='CSR status: FAILED'; statusDesc='CSR failed critical checks. Fix issues before submission.'; statusIcon='✖';} else if(hasWarn){panelClass='warn'; statusTitle='CSR status: WARNING'; statusDesc='CSR has warnings. Review details below before proceeding.'; statusIcon='⚠';} const rows=checks.map(c=>`<tr><td>${c.label}</td><td><span class="badge ${c.status==='ok'?'ok':c.status==='warn'?'warn':'bad'}">${c.status==='ok'?'PASS':c.status==='warn'?'WARN':'FAIL'}</span><span style="margin-left:8px">${c.result}</span></td></tr>`).join(''); return `<div class="decoder-section"><button class="decoder-section-head" type="button"><span>ECC Policy Checks</span><span>−</span></button><div class="decoder-section-body"><div class="panel ${panelClass}" style="margin:0 0 12px 0; padding:18px 18px 16px 18px;"><div class="csr-status-strong"><span>${statusTitle}</span><span style="margin-left:6px;">${statusIcon}</span></div><div class="csr-status-desc-tight">${statusDesc}</div></div><table class="mini-table decoder-policy-table"><thead><tr><th>Check</th><th>Result</th></tr></thead><tbody>${rows}</tbody></table></div></div>`; }
const renderCsrSubjectSection = (subject) => decoderSection('Subject', `<div class="decoder-kv-grid">${decoderKv('CN', subject.CN)}${decoderKv('O', subject.O)}${decoderKv('OU', subject.OU)}${decoderKv('L', subject.L)}${decoderKv('ST', subject.ST)}${decoderKv('C', subject.C)}${decoderKv('emailAddress', subject.emailAddress || subject.E)}</div>`);
const renderCsrRequestedExtensions = (info) => decoderSection('Requested Extensions', `<div class="decoder-kv-grid"><div class="decoder-kv"><div class="decoder-kv-label">SANs</div><div class="decoder-value-row"><div class="decoder-kv-value"><ul class="decoder-list">${(info.sans.length?info.sans:['N/A']).map(v=>`<li>${v}</li>`).join('')}</ul></div><button class="decoder-copy-btn" data-copy="${(info.sans.length?info.sans.join(', '):'N/A').replace(/"/g,'&quot;')}">Copy</button></div></div>${decoderKv('Key Usage', info.keyUsage.length ? info.keyUsage.join(', ') : 'N/A', true)}</div>`);
const renderCsrPublicKey = (info) => decoderSection('Public Key', `<div class="decoder-kv-grid">${decoderKv('Algorithm', info.keyAlgorithm)}${decoderKv('Curve', info.curveName, true)}${decoderKv('Key Size', info.keySize ? `${info.keySize} bits` : 'N/A')}${decoderLongValueSection('Public Key Hex', info.publicKeyHex)}</div>`);
const renderCsrSignature = (info) => decoderSection('Signature', `<div class="decoder-kv-grid">${decoderKv('Signature Algorithm', info.sigAlgorithm)}<div class="decoder-kv"><div class="decoder-kv-label">Signature Status</div><div class="decoder-kv-value">${info.signatureValid ? '<span class="decoder-badge decoder-badge-valid">✅ Valid signature</span>' : '<span class="decoder-badge decoder-badge-expired">❌ Invalid signature</span>'}</div></div>${decoderKvCode('SHA-256 Fingerprint', info.sha256, true)}${decoderKvCode('SHA-1 Fingerprint', info.sha1, true)}${decoderKvCode('MD5 Fingerprint', info.md5, true)}</div>`);
const renderRawPemSection = (pem) => decoderSection('Raw CSR', `<details class="decoder-long" open><summary>Show PEM</summary><pre class="decoder-raw">${pem.replace(/</g,'&lt;')}</pre></details>`, true);
function attachDecoderCopyAndCollapse(){ document.querySelectorAll('.decoder-copy-btn').forEach(btn => btn.onclick = () => navigator.clipboard.writeText(btn.getAttribute('data-copy')).catch(() => {})); document.querySelectorAll('.decoder-section-head').forEach(btn => btn.onclick = () => { const section = btn.closest('.decoder-section'); section.classList.toggle('collapsed'); btn.querySelector('span:last-child').textContent = section.classList.contains('collapsed') ? '+' : '−'; }); }
function renderCSR(pem){ const info=parseCsrLocal(pem); const checks=buildCsrPolicyChecks(info); results.innerHTML = `<div class="decoder-card"><h2 style="margin:0 0 8px 0;">Decoded ECC CSR</h2><div class="decoder-meta"><span class="decoder-chip">Certificate Signing Request</span><span class="decoder-chip">${info.curveName}</span></div>${renderPolicySection(checks)}${renderCsrSubjectSection(info.subject)}${renderCsrRequestedExtensions(info)}${renderCsrPublicKey(info)}${renderCsrSignature(info)}${renderRawPemSection(info.rawPem)}</div>`; attachDecoderCopyAndCollapse(); }
function decodeInput(){ hideDecoderError(); results.style.display='none'; results.innerHTML=''; const pem=normalisePem(pemInput.value); if(!pem || !(pem.includes('BEGIN CERTIFICATE REQUEST') || pem.includes('BEGIN NEW CERTIFICATE REQUEST'))){ showDecoderError('Could not decode input. Please check that it is a valid PEM-encoded ECC CSR.'); return; } try { renderCSR(pem); results.style.display='block'; } catch(e){ console.error(e); showDecoderError('Could not decode input. Please check that it is a valid PEM-encoded ECC CSR.'); } }
export function initDecoder(){
  decodeBtn.addEventListener('click', decodeInput);
  loadFileBtn.addEventListener('click', () => fileInput.click());
  fileInput.addEventListener('change', async (e) => { const file=e.target.files && e.target.files[0]; if (!file) return; try { pemInput.value = normalisePem(await readFileToPem(file)); hideDecoderError(); updateDecoderClearButton(); } catch { showDecoderError('Could not decode input. Please check that it is a valid PEM-encoded ECC CSR.'); } });
  loadExampleCsrBtn.addEventListener('click', () => { pemInput.value = EXAMPLE_ECC_CSR; hideDecoderError(); updateDecoderClearButton(); });
  clearBtn.addEventListener('click', () => { pemInput.value=''; fileInput.value=''; results.innerHTML=''; results.style.display='none'; hideDecoderError(); updateDecoderClearButton(); });
  pemInput.addEventListener('input', updateDecoderClearButton);
  updateDecoderClearButton();
}
